config/routes.rb
Rails.application.routes.draw do
  get 'rooms/show'
  mount ActionCable.server => '/cable'

  get 'home/index'
  get "templates/*id" => 'templates#show', as: :template, format: false
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  resources :users, only: [:new, :show, :create, :update]
  resources :photos, only: [:index, :show]
  resources :makeups, only: [:index, :show]
  resources :products, only: [:index, :show] do
    resources :comments
  end
  resources :events, only: [:index, :show] do
    resources :comments
  end
  resources :posts do
    resources :comments
  end

  delete 'logout', to: 'sessions#destroy'
  resources :sessions, only: [:new, :create]

  #user start
  namespace :users do
    resources :photos do
      member do
        post :like
        post :star
      end
    end
    resources :makeups
    resources :products
    resources :posts
    resources :events
  end
  #user end

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :images, as: :imageable
  has_many :comments, as: :commentable
  enum post_type: %i[photographer model dresser]

  validates :title, :content, :place, :time, :price, :outcome, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :nick_name, :phone_number, :gender, :place, presence: true
  validates :password, confirmation: true
  validates :nick_name, length: { maximum: 8 }
  validates :nick_name, uniqueness: true

  has_many :photos
  has_many :posts
  has_many :comments
  has_many :makeups
  has_many :products
  has_many :messages
  has_many :rooms

  before_create :create_remember_token
  # default_value
  attribute :nick_name, default: 'ds_' + SecureRandom.hex(10)
  attribute :avatar, default: '/avatar/default.jpeg'

  action_store :like, :photo, counter_cache: true
  action_store :star, :photo, counter_cache: true, user_counter_cache: true
  action_store :follow, :user, counter_cache: 'followers_count', user_counter_cache: 'following_count'

  def self.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def self.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

  def create_remember_token
    self.remember_token = User.encrypt(User.new_remember_token)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include ActionView::Helpers::DateHelper
  def index
    @posts = Post.all.recently
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
  end
end

app/controllers/user/photos_controller.rb
class User
  class PhotosController < ApplicationController
    before_action :set_photo, only: %i[show edit update destroy like star]
    def new
      @photo = Photo.new
      @uptoken = Image.new.uptoken
      @domain = Image.new.domain
    end

    def create
      @photo = current_user.photos.new(photo_params)
      if @photo.save
        params[:photo][:images][:url].each { |url| @photo.images.create(url: url) }
        redirect_to user_photos_path
      else
        render 'new'
      end
    end

    def index
      @photos = current_user.photos.recently
    end

    def destroy
      @photo.destroy
      redirect_to user_photos_path, notice: '相册已删除！'
    end

    def show
      @images = @photo.images
      respond_to do |format|
        format.html
        format.json { render json: @images.pluck(:url) }
      end
    end

    def like
      current_user.like_photo?(@photo) ? current_user.unlike_photo(@photo) : current_user.like_photo(@photo)
      redirect_to :root
    end

    def star
      current_user.star_photo?(@photo) ? current_user.unstar_photo(@photo) : current_user.star_photo(@photo)
      redirect_to :root
    end

    private

    def photo_params
      params.require(:photo).permit(:title, :brief_intro, :place, :key_word, :kind)
    end

    def set_photo
      @photo = current_user.photos.find(params[:id])
    end
  end
end

app/controllers/user/posts_controller.rb
class User
  class PostsController < ApplicationController
    before_action :set_post, only: %i[show edit update destroy star]
    def new
      @post = Post.new
      @uptoken = Image.new.uptoken
      @domain = Image.new.domain
    end

    def create
      @post = current_user.posts.new(post_params)
      if @post.save
        params[:post][:images][:url].each { |url| @post.images.create(url: url) }
        redirect_to :root
      else
        render 'new'
      end
    end

    def index
      @posts = current_user.posts.recently
    end

    def show
      @images = @post.images
      respond_to do |format|
        format.html
        format.json { render json: @images.pluck(:url) }
      end
    end

    def destroy
      @post.destroy
      redirect_to user_posts_path
    end

    def star
      current_user.create_action(:star, target: @post)
      redirect_to :back
    end

    private

    def post_params
      params.require(:post).permit(:title, :place, :time, :city, :price, :theme,
                                   :content, :outcome, :post_type, :has_clothing, :has_modelling)
    end

    def set_post
      @post = current_user.posts.find(params[:id])
    end
  end
end

app/controllers/users/events_controller.rb
module Users
  class EventsController < ApplicationController
    before_action :set_event, only: %i[show edit update destroy]
    def new
      @event = Event.new
      @uptoken = Image.new.uptoken
      @domain = Image.new.domain
    end

    def create
      @event = current_user.events.new(event_params)
      if @event.save
        params[:event][:images][:url].each { |url| @event.images.create(url: url) }
        redirect_to users_events_path
      else
        render 'new'
      end
    end

    def index
      @events = current_user.events.recently
    end

    def destroy
      @event.destroy
      redirect_to users_events_path, notice: '删除成功！'
    end

    def show
      @images = @event.images
      respond_to do |format|
        format.html
        format.json { render json: @images.pluck(:url) }
      end
    end

    private

    def event_params
      params.require(:event).permit(:title, :photo_style, :content, :content_raw,
                                    :city, :model_price, :cameramen_price, :start_time,
                                    :end_time, :deadline, :model_num, :cameramen_num)
    end

    def set_event
      @event = current_user.events.find(params[:id])
    end
  end
end

app/controllers/users/makeups_controller.rb
module Users
  class MakeupsController < ApplicationController
    before_action :set_makeup, only: %i[show edit update destroy]
    def new
      @makeup = Makeup.new
      @uptoken = Image.new.uptoken
      @domain = Image.new.domain
    end

    def create
      @makeup = current_user.makeups.new(makeup_params)
      if @makeup.save
        params[:makeup][:images][:url].each { |url| @makeup.images.create(url: url) }
        redirect_to users_makeups_path
      else
        render 'new'
      end
    end

    def index
      @makeups = current_user.makeups.recently
    end

    def destroy
      @makeup.destroy
      redirect_to users_makeups_path, notice: '删除成功！'
    end

    def show
      @images = @makeup.images
      respond_to do |format|
        format.html
        format.json { render json: @images.pluck(:url) }
      end
    end

    private

    def makeup_params
      params.require(:makeup).permit(:title, :brief_intro, :city, :price)
    end

    def set_makeup
      @makeup = current_user.makeups.find(params[:id])
    end
  end
end

app/controllers/users/photos_controller.rb
module Users
  class PhotosController < ApplicationController
    before_action :set_photo, only: %i[show edit update destroy like star]
    def new
      @photo = Photo.new
      @uptoken = Image.new.uptoken
      @domain = Image.new.domain
    end

    def create
      @photo = current_user.photos.new(photo_params)
      if @photo.save
        params[:photo][:images][:url].each { |url| @photo.images.create(url: url) }
        redirect_to users_photos_path
      else
        render 'new'
      end
    end

    def index
      @photos = current_user.photos.recently
    end

    def destroy
      @photo.destroy
      redirect_to users_photos_path, notice: '相册已删除！'
    end

    def show
      @images = @photo.images
      respond_to do |format|
        format.html
        format.json { render json: @images.pluck(:url) }
      end
    end

    def like
      current_user.like_photo?(@photo) ? current_user.unlike_photo(@photo) : current_user.like_photo(@photo)
      redirect_to :root
    end

    def star
      current_user.star_photo?(@photo) ? current_user.unstar_photo(@photo) : current_user.star_photo(@photo)
      redirect_to :root
    end

    private

    def photo_params
      params.require(:photo).permit(:title, :brief_intro, :place, :key_word, :kind)
    end

    def set_photo
      @photo = Photo.find(params[:id])
    end
  end
end

app/controllers/users/posts_controller.rb
module Users
  class PostsController < ApplicationController
    before_action :set_post, only: %i[show edit update destroy star]
    def new
      @post = Post.new
      @uptoken = Image.new.uptoken
      @domain = Image.new.domain
    end

    def create
      @post = current_user.posts.new(post_params)
      if @post.save
        params[:post][:images][:url].each { |url| @post.images.create(url: url) }
        redirect_to :root
      else
        render 'new'
      end
    end

    def index
      @posts = current_user.posts.recently
    end

    def show
      @images = @post.images
      respond_to do |format|
        format.html
        format.json { render json: @images.pluck(:url) }
      end
    end

    def destroy
      @post.destroy
      redirect_to users_posts_path
    end

    def star
      current_user.create_action(:star, target: @post)
      redirect_to :back
    end

    private

    def post_params
      params.require(:post).permit(:title, :place, :time, :city, :price, :theme,
                                   :content, :outcome, :post_type, :has_clothing, :has_modelling)
    end

    def set_post
      @post = current_user.posts.find(params[:id])
    end
  end
end

app/controllers/users/products_controller.rb
module Users
  class ProductsController < ApplicationController
    before_action :set_product, only: %i[show edit update destroy]
    def new
      @product = Product.new
      @uptoken = Image.new.uptoken
      @domain = Image.new.domain
    end

    def create
      @product = current_user.products.new(product_params)
      if @product.save
        params[:product][:images][:url].each { |url| @product.images.create(url: url) }
        redirect_to users_products_path
      else
        render 'new'
      end
    end

    def index
      @products = current_user.products.recently
    end

    def destroy
      @product.destroy
      redirect_to users_products_path, notice: '删除成功！'
    end

    def show
      @images = @product.images
      respond_to do |format|
        format.html
        format.json { render json: @images.pluck(:url) }
      end
    end

    private

    def product_params
      params.require(:product).permit(:title, :brief_intro, :city, :kind, :price,
                                      :ori_price, :free_shipping, :use_state)
    end

    def set_product
      @product = current_user.products.find(params[:id])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      redirect_to :root, notice: '登陆成功！'
    else
      render :new
    end
  end

  def show
    # @user = User.find(params[:id])
    @user = current_user
  end

  private

  def user_params
    params.require(:user).permit(:nick_name, :phone_number, :gender, :age, :place,
                                 :avatar, :password, :password_confirmation)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/posts/index.html.erb
<div class="bs-docs-container">
  <div class="bs-docs-section">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <div class="navbar-action right">
            <%= link_to '发布约拍',  new_users_post_path , class: 'btn btn-primary'%>
            <%= link_to '发布约妆',  new_users_makeup_path , class: 'btn btn-primary'%>
            <%= link_to '发布活动',  new_users_event_path , class: 'btn btn-primary'%>
            <%= link_to '发布宝贝',  new_users_product_path , class: 'btn btn-primary'%>
          </div>
          <div class="posts_section clear">
            <ul>
              <% @posts.each do |post| %>
              <li class="one_post">
                <div class="post_info">
                  <h4><%= post.title %></h4>
                  <div class="dropdown right">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                      <span class="glyphicon glyphicon-menu-down" aria-hidden="true"></span>
                    </a>
                    <ul class="dropdown-menu">
                      <li><%= link_to '删除', [:users, p], method: :delete, data:{confirm: '确定删除?'} %></li>
                    </ul>
                  </div>
                  <p><%= post.content %></p>
                  <div class="post_image">
                    <% post.images.first(4).each do |i| %>
                    <img src="<%= i.url %>" alt="">
                    <% end %>
                  </div>
                  <div class="post_detial">
                    <span><%= post.city %>
                      <span><%= time_ago_in_words(post.created_at)%><span>
                        <span>￥<%= post.price %></span>
                      </div>
                      <div class="visit_info">
                        <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
                        <span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span>
                        <span class="glyphicon glyphicon-comment" aria-hidden="true"></span>
                      </div>
                    </div>
                  </li>
                  <% end %>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <style media="screen">
    .bs-docs-section {background: #ececf3}
    .posts_section ul{padding: 0}
    .one_post{background: white; padding:10px; margin-bottom: 10px}
    .comment_list .comment_avatar{width:40px; height:40px;border: 1px solid #ffffff;border-radius:20px;overflow:hidden;float: left}
    .post_info a{text-decoration:none; color: black}
    .post_info a:hover{text-decoration:none;color:black}
    .post_image{width:1100px; height:180px; overflow:hidden}
    .post_image img{width:270px; height:auto;}
    .post_detial {margin-top: 10px; color: grey}
    .visit_info .glyphicon{color: #5bc0de;}
    </style>

app/views/users/posts/new.html.erb
<div class="bs-docs-container">
  <div class="bs-docs-section">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <%= form_for [:users, @post] do |f| %>
          <%= f.fields_for :image do |ff| %>
          <p>
            <div class="image_hidden"></div>
            <div class="image_preview"></div>
            <div class="container", id="container">
              <%= ff.label :image %><br>
              <%= ff.file_field :url %>
            </div>
          </p>
          <% end %>
          <p>
            <%= f.label :title %><br>
            <%= f.text_field :title %>
          </p>

          <p>
            <%= f.label :content %><br>
            <%= f.text_area :content %>
          </p>

          <p>
            <%= f.label :city %><br>
            <%= f.text_field :city %>
          </p>

          <p>
            <%= f.label :place %><br>
            <%= f.text_field :place %>
          </p>

          <p>
            <%= f.label :time %><br>
            <%= f.text_field :time %>
          </p>

          <p>
            <%= f.label :price %><br>
            <%= f.text_field :price %>
          </p>

          <p>
            <%= f.label :outcome %><br>
            <%= f.text_field :outcome %>
          </p>

          <p>
            <%= f.label :has_clothing %><br>
            <%= f.text_field :has_clothing %>
          </p>

          <p>
            <%= f.label :has_modelling %><br>
            <%= f.text_field :has_modelling %>
          </p>

          <p>
            <%= f.submit %>
          </p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
var uploader = Qiniu.uploader({
  runtimes: 'html5,html4',          //上传模式,依次退化
  browse_button: 'post_image_url',       //上传选择的点选按钮，**必需**
  uptoken : '<%= @uptoken %>',
  unique_names: true, // 默认 false，key为文件名。若开启该选项，SDK会为每个文件自动生成key（文件名）
  save_key: true, // 默认 false。若在服务端生成uptoken的上传策略中指定了 `sava_key`，则开启，SDK在前端将不对key进行任何处理
  domain: '<%= @domain %>', //bucket 域名，下载资源时用到，**必需**
  container: 'container',           //上传区域DOM ID，默认是browser_button的父元素，
  max_file_size: '5mb',           //最大文件体积限制
  max_retries: 3,                   //上传失败最大重试次数
  dragdrop: true,                   //开启可拖曳上传
  drop_element: 'container',        //拖曳上传区域元素的ID，拖曳文件或文件夹后可触发上传
  chunk_size: '1mb',                //分块上传时，每片的体积
  auto_start: true,                 //选择文件后自动上传，若关闭需要自己绑定事件触发上传
  init: {
    'FilesAdded': function(up, files) {
      plupload.each(files, function(file) {
        // 文件添加进队列后,处理相关的事情
        showPreview (file); // 预览
      });
    },
    'BeforeUpload': function(up, file) {
      // 每个文件上传前,处理相关的事情
    },
    'UploadProgress': function(up, file) {
      // 每个文件上传时,处理相关的事情
    },
    'FileUploaded': function(up, file, info) {

      // 每个文件上传成功后,处理相关的事情
      // 其中 info 是文件上传成功后，服务端返回的json，形式如
      // {
      //    "hash": "Fh8xVqod2MQ1mocfI4S4KpRL6D98",
      //    "key": "gogopher.jpg"
      //  }
      // 参考http://developer.qiniu.com/docs/v6/api/overview/up/response/simple-response.html
      var domain = up.getOption('domain');
      var res = $.parseJSON(info);
      var image_url = domain + '/' + res.key; //获取上传成功后的文件的Url
      console.log(info);
      console.log(image_url);
      $('.image_hidden').append('<input type="hidden" name="post[images][url][]" class="post_image" value="'+ image_url +'">');
    },
    'Error': function(up, err, errTip) {
      //上传出错时,处理相关的事情
    },
    'UploadComplete': function() {
      //队列文件处理完毕后,处理相关的事情
    },
    'Key': function(up, file) {
      // 若想在前端对每个文件的key进行个性化处理，可以配置该函数
      // 该配置必须要在 unique_names: false , save_key: false 时才生效
      var key = "";
      // do something with key here
      return key
    },
  }
});

//预览图片
function showPreview (file){
  var preloader = new mOxie.Image();
  preloader.onload = function() {
    preloader.downsize( 300, 300 );
    var src = preloader.getAsDataURL();
    var html = '<div><img src='+ src +' height="200" width="200"><span class="remove_btn">删除</span></div>'
    $('.image_preview').append(html);
  };
  preloader.load( file.getSource() );
}

//移除图片
$(document).on('click', '.remove_btn', function(){
  index = $('.remove_btn').index($(this))
  $(this).parent().remove();
  $($('.post_image')[index]).remove();
})

</script>