config/routes.rb
Rails.application.routes.draw do
  get 'rooms/show'
  mount ActionCable.server => '/cable'

  get 'home/index'
  get "templates/*id" => 'templates#show', as: :template, format: false
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  resources :users, only: [:new, :show, :create, :update]
  resources :photos, only: [:index, :show]
  resources :makeups, only: [:index, :show]
  resources :products, only: [:index, :show] do
    resources :comments
  end
  resources :events, only: [:index, :show] do
    resources :comments
  end
  resources :posts do
    resources :comments
  end

  delete 'logout', to: 'sessions#destroy'
  resources :sessions, only: [:new, :create]

  #user start
  namespace :users do
    resources :photos do
      member do
        post :like
        post :star
      end
    end
    resources :makeups
    resources :products
    resources :posts
    resources :events
  end
  #user end

end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user
  has_many :images, as: :imageable

  validates :title, :brief_intro, presence: true
  enum kind: %i[ancientry lolita cosplay]
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :nick_name, :phone_number, :gender, :place, presence: true
  validates :password, confirmation: true
  validates :nick_name, length: { maximum: 8 }
  validates :nick_name, uniqueness: true

  has_many :photos
  has_many :posts
  has_many :comments
  has_many :makeups
  has_many :products
  has_many :messages
  has_many :rooms

  before_create :create_remember_token
  # default_value
  attribute :nick_name, default: 'ds_' + SecureRandom.hex(10)
  attribute :avatar, default: '/avatar/default.jpeg'

  action_store :like, :photo, counter_cache: true
  action_store :star, :photo, counter_cache: true, user_counter_cache: true
  action_store :follow, :user, counter_cache: 'followers_count', user_counter_cache: 'following_count'

  def self.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def self.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

  def create_remember_token
    self.remember_token = User.encrypt(User.new_remember_token)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  include ActionView::Helpers::DateHelper

  def show
    @photo = Photo.find(params[:id])
    @images = @photo.images
    respond_to do |format|
      format.html
      format.json { render json: @images.pluck(:url) }
    end
  end
end

app/controllers/user/photos_controller.rb
class User
  class PhotosController < ApplicationController
    before_action :set_photo, only: %i[show edit update destroy like star]
    def new
      @photo = Photo.new
      @uptoken = Image.new.uptoken
      @domain = Image.new.domain
    end

    def create
      @photo = current_user.photos.new(photo_params)
      if @photo.save
        params[:photo][:images][:url].each { |url| @photo.images.create(url: url) }
        redirect_to user_photos_path
      else
        render 'new'
      end
    end

    def index
      @photos = current_user.photos.recently
    end

    def destroy
      @photo.destroy
      redirect_to user_photos_path, notice: '相册已删除！'
    end

    def show
      @images = @photo.images
      respond_to do |format|
        format.html
        format.json { render json: @images.pluck(:url) }
      end
    end

    def like
      current_user.like_photo?(@photo) ? current_user.unlike_photo(@photo) : current_user.like_photo(@photo)
      redirect_to :root
    end

    def star
      current_user.star_photo?(@photo) ? current_user.unstar_photo(@photo) : current_user.star_photo(@photo)
      redirect_to :root
    end

    private

    def photo_params
      params.require(:photo).permit(:title, :brief_intro, :place, :key_word, :kind)
    end

    def set_photo
      @photo = current_user.photos.find(params[:id])
    end
  end
end

app/controllers/user/posts_controller.rb
class User
  class PostsController < ApplicationController
    before_action :set_post, only: %i[show edit update destroy star]
    def new
      @post = Post.new
      @uptoken = Image.new.uptoken
      @domain = Image.new.domain
    end

    def create
      @post = current_user.posts.new(post_params)
      if @post.save
        params[:post][:images][:url].each { |url| @post.images.create(url: url) }
        redirect_to :root
      else
        render 'new'
      end
    end

    def index
      @posts = current_user.posts.recently
    end

    def show
      @images = @post.images
      respond_to do |format|
        format.html
        format.json { render json: @images.pluck(:url) }
      end
    end

    def destroy
      @post.destroy
      redirect_to user_posts_path
    end

    def star
      current_user.create_action(:star, target: @post)
      redirect_to :back
    end

    private

    def post_params
      params.require(:post).permit(:title, :place, :time, :city, :price, :theme,
                                   :content, :outcome, :post_type, :has_clothing, :has_modelling)
    end

    def set_post
      @post = current_user.posts.find(params[:id])
    end
  end
end

app/controllers/users/events_controller.rb
module Users
  class EventsController < ApplicationController
    before_action :set_event, only: %i[show edit update destroy]
    def new
      @event = Event.new
      @uptoken = Image.new.uptoken
      @domain = Image.new.domain
    end

    def create
      @event = current_user.events.new(event_params)
      if @event.save
        params[:event][:images][:url].each { |url| @event.images.create(url: url) }
        redirect_to users_events_path
      else
        render 'new'
      end
    end

    def index
      @events = current_user.events.recently
    end

    def destroy
      @event.destroy
      redirect_to users_events_path, notice: '删除成功！'
    end

    def show
      @images = @event.images
      respond_to do |format|
        format.html
        format.json { render json: @images.pluck(:url) }
      end
    end

    private

    def event_params
      params.require(:event).permit(:title, :photo_style, :content, :content_raw,
                                    :city, :model_price, :cameramen_price, :start_time,
                                    :end_time, :deadline, :model_num, :cameramen_num)
    end

    def set_event
      @event = current_user.events.find(params[:id])
    end
  end
end

app/controllers/users/makeups_controller.rb
module Users
  class MakeupsController < ApplicationController
    before_action :set_makeup, only: %i[show edit update destroy]
    def new
      @makeup = Makeup.new
      @uptoken = Image.new.uptoken
      @domain = Image.new.domain
    end

    def create
      @makeup = current_user.makeups.new(makeup_params)
      if @makeup.save
        params[:makeup][:images][:url].each { |url| @makeup.images.create(url: url) }
        redirect_to users_makeups_path
      else
        render 'new'
      end
    end

    def index
      @makeups = current_user.makeups.recently
    end

    def destroy
      @makeup.destroy
      redirect_to users_makeups_path, notice: '删除成功！'
    end

    def show
      @images = @makeup.images
      respond_to do |format|
        format.html
        format.json { render json: @images.pluck(:url) }
      end
    end

    private

    def makeup_params
      params.require(:makeup).permit(:title, :brief_intro, :city, :price)
    end

    def set_makeup
      @makeup = current_user.makeups.find(params[:id])
    end
  end
end

app/controllers/users/photos_controller.rb
module Users
  class PhotosController < ApplicationController
    before_action :set_photo, only: %i[show edit update destroy like star]
    def new
      @photo = Photo.new
      @uptoken = Image.new.uptoken
      @domain = Image.new.domain
    end

    def create
      @photo = current_user.photos.new(photo_params)
      if @photo.save
        params[:photo][:images][:url].each { |url| @photo.images.create(url: url) }
        redirect_to users_photos_path
      else
        render 'new'
      end
    end

    def index
      @photos = current_user.photos.recently
    end

    def destroy
      @photo.destroy
      redirect_to users_photos_path, notice: '相册已删除！'
    end

    def show
      @images = @photo.images
      respond_to do |format|
        format.html
        format.json { render json: @images.pluck(:url) }
      end
    end

    def like
      current_user.like_photo?(@photo) ? current_user.unlike_photo(@photo) : current_user.like_photo(@photo)
      redirect_to :root
    end

    def star
      current_user.star_photo?(@photo) ? current_user.unstar_photo(@photo) : current_user.star_photo(@photo)
      redirect_to :root
    end

    private

    def photo_params
      params.require(:photo).permit(:title, :brief_intro, :place, :key_word, :kind)
    end

    def set_photo
      @photo = Photo.find(params[:id])
    end
  end
end

app/controllers/users/posts_controller.rb
module Users
  class PostsController < ApplicationController
    before_action :set_post, only: %i[show edit update destroy star]
    def new
      @post = Post.new
      @uptoken = Image.new.uptoken
      @domain = Image.new.domain
    end

    def create
      @post = current_user.posts.new(post_params)
      if @post.save
        params[:post][:images][:url].each { |url| @post.images.create(url: url) }
        redirect_to :root
      else
        render 'new'
      end
    end

    def index
      @posts = current_user.posts.recently
    end

    def show
      @images = @post.images
      respond_to do |format|
        format.html
        format.json { render json: @images.pluck(:url) }
      end
    end

    def destroy
      @post.destroy
      redirect_to users_posts_path
    end

    def star
      current_user.create_action(:star, target: @post)
      redirect_to :back
    end

    private

    def post_params
      params.require(:post).permit(:title, :place, :time, :city, :price, :theme,
                                   :content, :outcome, :post_type, :has_clothing, :has_modelling)
    end

    def set_post
      @post = current_user.posts.find(params[:id])
    end
  end
end

app/controllers/users/products_controller.rb
module Users
  class ProductsController < ApplicationController
    before_action :set_product, only: %i[show edit update destroy]
    def new
      @product = Product.new
      @uptoken = Image.new.uptoken
      @domain = Image.new.domain
    end

    def create
      @product = current_user.products.new(product_params)
      if @product.save
        params[:product][:images][:url].each { |url| @product.images.create(url: url) }
        redirect_to users_products_path
      else
        render 'new'
      end
    end

    def index
      @products = current_user.products.recently
    end

    def destroy
      @product.destroy
      redirect_to users_products_path, notice: '删除成功！'
    end

    def show
      @images = @product.images
      respond_to do |format|
        format.html
        format.json { render json: @images.pluck(:url) }
      end
    end

    private

    def product_params
      params.require(:product).permit(:title, :brief_intro, :city, :kind, :price,
                                      :ori_price, :free_shipping, :use_state)
    end

    def set_product
      @product = current_user.products.find(params[:id])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      redirect_to :root, notice: '登陆成功！'
    else
      render :new
    end
  end

  def show
    # @user = User.find(params[:id])
    @user = current_user
  end

  private

  def user_params
    params.require(:user).permit(:nick_name, :phone_number, :gender, :age, :place,
                                 :avatar, :password, :password_confirmation)
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/photos/index.html.erb
<div class="bs-docs-container">
  <div class="bs-docs-section">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <div class="navbar-action right">
            <%= link_to '上传照片', new_users_photo_path , class: 'btn btn-primary'%>
          </div>
          <div class="photo-list clear">
            <ul>
              <% @photos.each do |p| %>
              <li>
                <div class="img_wrapper">
                  <img src="<%= p.images.first.url %>">
                  <p class="desc img_title"><%= link_to p.title, users_photo_path(p), class:'white_link'%> </p>
                  <p class="desc img_count"><%= p.images.count %>张图片<span class="img_time"><%= p.created_at.strftime('%Y-%m-%d') %></span></p>
                  <%= link_to [:users, p], method: :delete, data:{confirm: '确定删除相册?'} do %>
                   <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                  <% end %>
                </div>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<style media="screen">
.navbar-action {margin-top:20px}
.photo-list li{float: left;width:23%; height:200px;overflow: hidden;margin:1%}
.photo-list img{width: 200px;min-height: 200px}
.photo-list .img_wrapper{position:relative;}
.photo-list .desc{position:absolute;left:5%; color:white; font-weight:200; z-index: 111;}
.photo-list .img_title{top:155px;}
.img_count{top:175px;font-size: 13px}
.photo-list .img_wrapper .img_time{margin-left:10px;font-size: 13px}
.glyphicon-trash {position: absolute; left:72%; top:5px;font-size:20px; display: none;}
.img_wrapper:hover .glyphicon-trash{display: block}
.glyphicon-trash:hover{cursor: pointer}
</style>

app/views/users/photos/show.html.erb
<style>
    .img-preview{
      width: 1000px;
      margin: 0 auto;
    }
    .img-row {
      /*margin-bottom: 8px;*/
    }
    .img-row:after {
      content: "";
      display: block;
      clear: both;
    }
    .img-box {
      float: left;
    }
    .img-line .img-box:first-child {
      padding-left: 0;
    }
</style>
<div class="bs-docs-container">
  <div class="bs-docs-section">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <div class="img-preview">

          </div>
        </div>
      </div>
    </div>
  </div>
</div>



	<script>
    function Barrels($ct) {    //0 创建对象
      this.$ct = $ct;
      // this.imgNum = 3;
      this.baseHeight = 200; //！！！！！！预设行高！！！！！！
      this.rowList = [];    //创建空数组，用来放置拿到的图片
      this.loadImg();       //开始下载图片
    }
    Barrels.prototype = {
      loadImg: function() {   //2 加载图片
        var _this = this;    //缓存全局this
        $.ajax({
          url: '/user/photos/<%= @photo.id %>',
          type: 'get',
          dataType: 'json',
          success: function(data){
            var imgUrls = data;
            $.each(imgUrls,function(idx, url){
              var img = new Image();
              img.src = url;
              img.onload = function(){
                var originWidth = img.width,
                    originHeight = img.height,
                    ratio = originWidth/originHeight;//！！！！！！得到图片原始比例
                var imgInfo = {
                  target: $(img),
                  width: _this.baseHeight*ratio,//！！！！！！首次缩放
                  height: _this.baseHeight,
                  ratio: ratio
                };
                _this.render(imgInfo);
              };
            });
          }
        });

      },
      render: function(imgInfo){    // 3 预先摆放
        var _this = this;
        var rowList = this.rowList,
            rowWidth = 0,
            rowHeight = 0,
            clientWidth = this.$ct.width(),
            lastImgInfo = imgInfo;
        this.rowList.push(imgInfo);
        $.each(rowList,function(idx, imgInfo){
          rowWidth += imgInfo.width;
          if(rowWidth  > clientWidth ){
            // rowList.pop();
            rowWidth = rowWidth - lastImgInfo.width;
            rowHeight = clientWidth * _this.baseHeight / rowWidth;//！！！！！！再次缩放
            _this.createRow(rowHeight);
            _this.rowList = [];
            _this.rowList.push(lastImgInfo);
          }else {
            _this.createRow(_this.baseHeight);
          }
        });
      },
      createRow: function(rowHeight){    // 4 正式摆放图片
        // console.log('createRow');
        var $rowCt = $('<div class="img-row"></div>');
        $.each(this.rowList, function(idx, imgInfo){
          var $imgCt = $('<div class="img-box"></div>'),
              $img = imgInfo.target;
              $img.height(rowHeight);
              $imgCt.append($img);
              $rowCt.append($imgCt);
        });
        // console.log(this.$ct);
        this.$ct.append($rowCt);
      },
    };
    var barrels = new Barrels($('.img-preview'));
	</script>