config/routes.rb
Rails.application.routes.draw do
  get 'rooms/show'
  mount ActionCable.server => '/cable'

  get 'home/index'
  get "templates/*id" => 'templates#show', as: :template, format: false
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  resources :users, only: [:new, :show, :create, :update]
  resources :photos, only: [:index, :show]
  resources :makeups, only: [:index, :show]
  resources :products, only: [:index, :show] do
    resources :comments
  end
  resources :events, only: [:index, :show] do
    resources :comments
  end
  resources :posts do
    resources :comments
  end

  delete 'logout', to: 'sessions#destroy'
  resources :sessions, only: [:new, :create]

  #user start
  namespace :users do
    resources :photos do
      member do
        post :like
        post :star
      end
    end
    resources :makeups
    resources :products
    resources :posts
    resources :events
  end
  #user end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  include DewSet::Tools
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  belongs_to :original, class_name: 'Comment', foreign_key: 'original_id', optional: true
  belongs_to :original_author, class_name: 'User', foreign_key: 'original_author_id', optional: true
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :images, as: :imageable
  has_many :comments, as: :commentable

  validates :title, :photo_style, :content, :content_raw, :city, :model_price, :cameramen_price, :start_time,
            :end_time, :deadline, :model_num, :cameramen_num, presence: true
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :imageable, polymorphic: true
  def uptoken
    bucket = config[:bucket_name]
    # put_policy = Qiniu::Auth::PutPolicy.new(bucket, nil, 3600)
    put_policy = Qiniu::Auth::PutPolicy.new('ceshi-photo:aaa.jpeg', nil, 3600)
    put_policy.callback_body = config[:callback_body]
    Qiniu::Auth.generate_uptoken(put_policy) # uptoken
    # { uptoken: uptoken, bucket: bucket, domain: domain }
  end

  def config
    @config ||= Rails.application.config_for(:qiniu_storage)
  end

  def domain
    "http://#{Qiniu::QiniuDomain['ceshi-photo']}"
  end
end

app/models/makeup.rb
class Makeup < ApplicationRecord
  belongs_to :user
  has_many :images, as: :imageable

  validates :title, :brief_intro, :price, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :from_user, class_name: 'User', foreign_key: 'user_id'
  belongs_to :to_user, class_name: 'User', foreign_key: 'to_user_id'
  belongs_to :room
  after_create_commit { MessageBroadcastJob.perform_later(unread_count, self) }

  scope :unread, -> { where(read: false) }

  def unread_count
    Message.unread.where(to_user_id: to_user_id).count
  end
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user
  has_many :images, as: :imageable

  validates :title, :brief_intro, presence: true
  enum kind: %i[ancientry lolita cosplay]
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :images, as: :imageable
  has_many :comments, as: :commentable
  enum post_type: %i[photographer model dresser]

  validates :title, :content, :place, :time, :price, :outcome, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many :images, as: :imageable
  has_many :comments, as: :commentable

  validates :title, :brief_intro, :city, :kind, :price, :free_shipping, :use_state, presence: true
  enum kind: %i[clothing headwear prop]
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :from_user, class_name: 'User', foreign_key: 'user_id'
  belongs_to :to_user, class_name: 'User', foreign_key: 'to_user_id'
  has_many :messages
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :nick_name, :phone_number, :gender, :place, presence: true
  validates :password, confirmation: true
  validates :nick_name, length: { maximum: 8 }
  validates :nick_name, uniqueness: true

  has_many :photos
  has_many :posts
  has_many :comments
  has_many :makeups
  has_many :products
  has_many :messages
  has_many :rooms

  before_create :create_remember_token
  # default_value
  attribute :nick_name, default: 'ds_' + SecureRandom.hex(10)
  attribute :avatar, default: '/avatar/default.jpeg'

  action_store :like, :photo, counter_cache: true
  action_store :star, :photo, counter_cache: true, user_counter_cache: true
  action_store :follow, :user, counter_cache: 'followers_count', user_counter_cache: 'following_count'

  def self.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def self.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

  def create_remember_token
    self.remember_token = User.encrypt(User.new_remember_token)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @photos = Photo.all.includes(:user).recently.limit(5)
    @posts = Post.all.recently.limit(5)
    @comment = Comment.new
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include ActionView::Helpers::DateHelper
  def index
    @posts = Post.all.recently
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def show
    @room = current_user.rooms.find_by(to_user_id: params[:to_user_id]) ||
            Room.find_by(to_user_id: current_user.id, user_id: params[:to_user_id]) ||
            current_user.rooms.create!(to_user_id: params[:to_user_id])
    @messages = @room.messages.includes(:from_user)
    @messages.unread.update_all(read: true)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      redirect_to :root, notice: '登陆成功！'
    else
      render :new
    end
  end

  def show
    # @user = User.find(params[:id])
    @user = current_user
  end

  private

  def user_params
    params.require(:user).permit(:nick_name, :phone_number, :gender, :age, :place,
                                 :avatar, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update(remember_token: User.encrypt(remember_token))
    self.current_user = user
  end

  def sign_out
    User.find(params[:id]).remember_token = nil
    # self.remember_token = nil
    cookies.delete(:remember_token)
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="bs-docs-container">
  <div class="bs-docs-section">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <div class="photos_section">
            <ul>
              <% @photos.each do |photo| %>
              <li>
                <div class="img_wrapper">
                  <img src="<%= photo.images.first.url %>">
                  <div class="img_desc">
                    <span class="img_title"><%= link_to photo.title, photo_path(photo), class:'white_link'%> </span>
                    <span class="img_author"><%= photo.user.nick_name %></span>
                  </div>
                </div>
                <p>
                  <%= link_to '点赞', like_users_photo_path(photo), method: :post %><span><%= photo.likes_count %></span>
                  <%= link_to '收藏', star_users_photo_path(photo), method: :post %>
                </p>
              </li>
              <% end %>
            </ul>
          </div>
          <div class="posts_section clear">
            <ul>
              <% @posts.each do |post| %>
              <li>
                <div class="">
                  <p><%= post.title %></p>
                  <p><%= post.content %></p>
                </div>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<style media="screen">
.photos_section li{float: left;height:300px;width:23%;}
.photos_section .img_wrapper{position:relative; height:200px;overflow: hidden;margin:1%}
.photos_section .img_desc{position:absolute;padding:3%;height: 40px;width:200px;bottom:0px;color:white;font-weight: 200;background:rgba(23, 10, 10, 0.45)}
.photos_section img{width: 200px;min-height: 200px}
.photos_section .img_title{font-size:14px}
.photos_section .img_author{float: right}
.posts_section .input_content{width:70%;height: 30px}
.comment_list .comment_avatar{width:40px; height:40px;border: 1px solid #ffffff;border-radius:20px;overflow:hidden;float: left}
.comment_list .replay_list .comment_author{color: #5bc0de}
</style>